name: Build Release Version

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v6

    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@11d4d83c63a6ce61b32d8a9c4faddbdb04fe9917 # v6

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Upload Binary JAR
      uses: actions/upload-artifact@v7
      with:
        path: |
          build/libs/*.jar
          !build/libs/*-sources.jar
        archive: false

    - name: Upload Sources JAR
      uses: actions/upload-artifact@v7
      with:
        path: build/libs/*-sources.jar
        archive: false
